apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: enjoyyy-doppler
  namespace: enjoyyy
spec:
  tokenSecret:
    name: doppler-token-secret
  managedSecret:
    name: enjoyyy-managed
    type: Opaque
  project: enjoyyy
  config: dev
  resyncSeconds: 60
