apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: enjoyyy

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - doppler-secret.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: enjoyyy
    includeSelectors: false

images:
  - name: 192.168.1.247:8080/enjoyyy/backend
    newTag: latest
  - name: 192.168.1.247:8080/enjoyyy/frontend
    newTag: latest
